language: node_js
node_js:
    - stable
script: bash ./scripts/deploy.sh
env:
    global:
        - ENCRYPTION_LABEL: '60d7449a1baf'
        - COMMIT_AUTHOR_EMAIL: '21034047+hanzhi713@users.noreply.github.com'
install:
    - npm install -g codecov http-server
    - npm ci
after_success:
    - codecov